### ISSUE TITLE
CrankShaft Logo

### ISSUE THREAD

**Issue by TheWebTech** [TheWebTech/CrankShaft#20]
Every big project needs a banner to fly.  If you have great design skills or atleast want to be apart of the process of picking a Logo. Chime in here.

If someone has replied that they want to contribute their design skills, that does not mean you cannot. If we get multiple submissions that makes things easier and we can choose from the best.

Things to keep in mind - This is not an official HubSpot Repo, we do not own any of their copyrights or trademarks. That does not mean we cannot keep a visual theme.

If you want to design a logo for CrankShaft you can do so either by submitting a pull request with your logo files OR by posting the logo to this issue.

**Comment by joneichler** [comment]
I'll take a stab at it.

**Comment by TheWebTech** [comment]
Andreas Wessoly sent me these concepts.
<img width="203" alt="crankshaft draft" src="https://user-images.githubusercontent.com/5492388/57081416-40e55900-6cba-11e9-9267-642d2d922920.PNG">

What I like 
- it's a semi-literal crankshaft interpretation
- It's got a similar-to HubSpot aesthetic without being overt about it.
- I can see this thing being animated

What maybe could be improved upon
- I'm not a mechanic - when I look at it I do see Pistons which is cool but I think a literal crankshaft looks more like this: ![CrankShaft](https://www.lycoming.com/sites/default/files/header-part_1_0.png)

**Comment by joneichler** [comment]
Pistons are mounted to the crankshaft  
![download](https://user-images.githubusercontent.com/854776/57100054-997d1c00-6ce3-11e9-879d-fd241fb461a4.jpeg)

**Comment by joneichler** [comment]
![Artboard 1@3x-100](https://user-images.githubusercontent.com/854776/57103196-c4b73980-6cea-11e9-90e1-c2317f03ee30.jpg)

**Comment by TheWebTech** [comment]
oOOooohh. thank you for the explanation, my mechanic father would not be proud of me lol. 

I like the logo direction you went with. Pretty dang spiffy.

**Comment by joneichler** [comment]
Thanks, If you have any thoughts about it let me know and I'll put some final touches and then do a pull request with several files size and types / icon buttons.

**Comment by TheWebTech** [comment]
feels like the icon may need some minor clean up - like the lines may not line up (I get that that it's intentional that there's like 1-2px gap along the sides similar to the photos. I'm not talking about that) just looks like the lines are not actually parallel
I could be wrong, just looks like it to me.
![](https://spin.d.pr/o6246U+)

also really minor the circles could be centered better on the ends of the lines.
Otherwise I personally love it.


Another super minor think, but maybe reduce the letter-spacing very slightly, might just be me, it's just slightly hard to read. (keep the effect just saying a little less might make it easier on the eyes)


Again those notes are super minor.

I think we once you're done tweaking maybe we'll post it to the slack and do a /poll and see if people like it, if majority like it by end of day today, then we'll go with it

**Comment by joneichler** [comment]
Okay Great, I probably won't get back around to it until later tonight and Ill DM it to you on slack so you can do whatever you want as far as the Poll Goes.

**Comment by TheWebTech** [comment]
Discussed in slack, just making sure it's logged here.
*if anyone wants to contribute their logo ideas, you have until next Friday*
If by Friday no one has submitted anything new we’ll go based on the poll we took above(including new votes that come in)

And polish whichever logo the majority wanted.

This is to avoid the creators of the existing logos going through a lot of trouble to polish them up or make changes that might get scrapped if the logo isn't chosen. This also buys time for those who are interested in designing a logo that didn't yet get a chance.

The due date of Friday, gives a weekend and a full work week to come up with something.

**Comment by Andreas1281** [comment]
Hello everyone, here is another Logo Idea that i came up with:
![Bildschirmfoto 2019-05-08 um 20 26 38](https://user-images.githubusercontent.com/757325/57399889-80d4a080-71d2-11e9-903d-1277d7e5fc44.jpg)

And also with a more "automotive" Font (DDC Hardware): 
![Bildschirmfoto 2019-05-08 um 21 19 00](https://user-images.githubusercontent.com/757325/57402858-8503bc80-71d8-11e9-84f7-ebcafd2b1ff2.jpg)

**Comment by TheWebTech** [comment]
another logo contender from @joneichler 
![](https://spin.d.pr/HKgfqe+)
We're going to hold a vote early I think due to popular demand in slack

**Comment by TheWebTech** [comment]
Jon Eichler's logo won the vote.

If someone wants to contest this the policy is as follows:
For those that wanted  logo. If you post an issue and can get 5 more “votes” than Ikes got(meaning Ikes total from the poll + 5 people posting and confirming they will vote 1 single other logo) we can do a revote. Otherwise we’re moving on to the code and docs for the project and I hope everyone can come along and help with that stuff too.
