### ISSUE TITLE
Review if Clearfix css is necessary anymore

### ISSUE THREAD

**Issue by TheWebTech** [TheWebTech/CrankShaft#29]
Line 350 of the cs-grid.css file.
https://github.com/TheWebTech/CrankShaft/blob/245d6ea96bb6f566ffcb90224db0e7e30b8b49d3/theme/cs-grid.css#L346-L361
 If new grid doesn't use floats, there's no purpose for clearfix.

**Comment by johnsfuller** [comment]
Wait, isn't this bit of css in hubspot's layout.css file for drag n drop design manager templates?

**Comment by TheWebTech** [comment]
I believe it possibly is. I don't have a link to that file handy to check If it is in the layout.css that HS injects. Then it's unnecessary to have in our file, it'd just be redundant.

On coded templates, if our grid isn't using floats either, then there's no point in having it.

I'm leaning toward it can probably get removed.

**Comment by johnsfuller** [comment]
[here's the link](https://cdn2.hubspot.net/hub/-1/hub_generated/template_assets/1495141902090/hubspot_default/shared/responsive/layout.css) to the layout.css file

**Comment by TheWebTech** [comment]
yep it's 100% in there.

It's redundant then **I think we're good to remove it.**

Anyone wanna go for it? easy small task, to get your foot in the door working with git

**Comment by joneichler** [comment]
I'll take a stab at it (git newb here)

**Comment by TheWebTech** [comment]
fixed in #39
