### ISSUE TITLE
Use HubL to Generate grid CSS

### ISSUE THREAD

**Issue by TheWebTech** [TheWebTech/CrankShaft#33]
Part of #8 basically. The gist is let's update the css to use HubL to loop through generating the classes. Otherwise this is going to be tedious to update/maintain.

https://github.com/TheWebTech/CrankShaft/blob/master/CrankShaft/code/cs/cs-grid.css#L441-L2532

**Comment by TheWebTech** [comment]
Example code

```
{%- for i in range(1, 12) -%}

  .col-{{i}} {
 -webkit-box-flex: 0;
  -ms-flex: 0 0 8.333333%;
  flex: 0 0 8.333333%;
  max-width: 8.333333%;
  }
  {%- endfor -%}
```

You'd just need to have it then calculate that %.  Which is somewhat simple math.
bootstrap has a 12 col grid.
100% = 12


You'll know you have it right, if it matches the code you already see there.

**Comment by adesignl** [comment]
why not use the span1 - span12 class so when you use the drag and drop it still works

You can customize it for other situations.

**Comment by TheWebTech** [comment]
Maybe I wasn't clear, that IS the plan, but we're going to support both class names. as the spans are specific to one screensize.
I have that as a separate issue #32 

Sorry I'm trying to break down all the steps into smaller chunks so that people have clear todo's on how to help. Otherwise telling people "okay let's build the framework" is an abstract daunting task. This one maybe I drilled down too much. idk.

**Comment by adesignl** [comment]
Its cool.
I was just going issue by issue.

**Comment by TheWebTech** [comment]
helped Andreas Wessoly with the math for it so here's the math for generating the widths
```
{% set colwidth = (100/12) * i  %}
width: {{colwidth}}%;
*width:{{colwidth}}%;
```

**Comment by TheWebTech** [comment]
going to close this issue, we have some further related changes to make in Hublizing the grid but for the sake of keeping the issues single topic, I'll create new issues for those.
