### ISSUE TITLE
Create base custom module to be used as a starter to jumpstart development of crankshaft compatible custom modules

### ISSUE THREAD

**Issue by TheWebTech** [TheWebTech/CrankShaft#44]
Basic jist, create a super bare bones custom module, based on any ideas from #40 it can be updated later as we come up with more best practices or ideas.

It can be as stupid simple as just having the html pane have content, with just a div wrapper and that's it.

We'll expand on it as we go.

To do this someone could create the custom module in the design manager and use FTP to download it into the /modules folder of crankshaft.

**Comment by dennisedson** [comment]
created basic module here #70 
inserted rich text for now.  obviously, this is skeletal and can be updated

**Comment by TheWebTech** [comment]
Closing because #70 resolved this. Good work Dennis!

We'll expand on it over time. it's good to have something in there as good start.
