### ISSUE TITLE
Add Debug Variable Macro

### ISSUE THREAD

**Issue by TheWebTech** [TheWebTech/CrankShaft#63]
Idea is - a macro that you pass a variable into. When you do that it pretty prints the variable, but only if hsDebug=true. This is a utility that can be used to debug your code without risking that code being seen live.

This would go in theme-macros.css

If you have additional ideas for this go for it!

**Comment by jfudman** [comment]
```
{% macro debugger( var ) %}
<pre style="white-space: pre-wrap; word-wrap: break-word; padding: 1em; background-color: #f1f1f1; color: #333;">
  {{ var|pprint }}
</pre>
{% endmacro %}
```

**Comment by adesignl** [comment]
{% macro debugger( var ) %}{% if request.query_dict.hsDebug == true %}
<pre style="white-space: pre-wrap; word-wrap: break-word; padding: 1em; background-color: #f1f1f1; color: #333;">
  {{ var|pprint }}
</pre>{% endif %}
{% endmacro %}On May 14, 2019 9:20 AM, John Fuller <notifications@github.com> wrote:{% macro debugger( var ) %}
<pre style="white-space: pre-wrap; word-wrap: break-word; padding: 1em; background-color: #f1f1f1; color: #333;">
  {{ var|pprint }}
</pre>
{% endmacro %}

**Comment by johnsfuller** [comment]
haha I deleted comment after I realized I forgot the debug request. Cheers

**Comment by TheWebTech** [comment]
lol aside from your email reply stuff ending up in the post, this seems like this might be perfect.

Someone add it to theme-macros.css! 👍
