### ISSUE TITLE
Convert Bootstrap's grid to a css file with HubL

### ISSUE THREAD

**Issue by TheWebTech** [TheWebTech/CrankShaft#8]
Creating this as an issue to make this easier to track and collaborate on.
We want to take just the grid part of Bootstrap, and pull it into a css file that can be used on hubspot, ultimate goal being that we could use HubL to change some of the things that currently have sass variables in normal bootstrap.

minimum viable thing would be to just have the straight outputted CSS for the grid in this repo. Super awesome bonus would be having some hubl vars - not required though.

Even more awesome- if any of the css that's repetitive used hubl to generate it, making it easier to maintain. not required at all though.

Mark Ryba and AJ feel free to assign to yourselves too when you join. We can all collab on this.

**Comment by TheWebTech** [comment]
We'll use https://github.com/TheWebTech/CrankShaft/tree/grid-feature for working on this feature.
Contribute to that branch. When working on the grid.

**Comment by TheWebTech** [comment]
To point out where we're implementing the grid code for anyone who wants to hop in and help
https://github.com/TheWebTech/CrankShaft/blob/master/CrankShaft/code/cs/cs-grid.css#L441-L2532

Updated link to code.

**Comment by dennisedson** [comment]
> We'll use https://github.com/TheWebTech/CrankShaft/tree/grid-feature for working on this feature.
> Contribute to that branch. When working on the grid.

the url 404s

**Comment by TheWebTech** [comment]
Sorry I merged that branch in. I'll update links to the files. To keep it clear where they are.

a new branch can be created for working on this.

**Comment by TheWebTech** [comment]
Let me know if you don't feel comfortable making your own branch or working in a fork, I can create a branch for it if necessary.

branch name can be whatever, just name it something related to the grid.

**Comment by TheWebTech** [comment]
I think this is actually fully done now, so anything we want to add is just improvements.
